version: '3.3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    environment:
      - ACME_DNS_API_BASE=https://auth.acme-dns.io
      - ACME_DNS_STORAGE_PATH=/acme-dns
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
      - ./acme-dns:/acme-dns
      # Add folder with dynamic configuration yml
      - ./configurations:/configurations
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.le-5ra.de`)"
      - "traefik.http.routers.traefik-secure.middlewares=secureHeaders@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
#      - "traefik.http.routers.traefik-secure.tls.certresolver=le-dns" # limit rate
      - "traefik.http.routers.traefik-secure.tls.certresolver=zerossl" # unlimited rate
      - "traefik.http.routers.traefik-secure.tls=true"
      
networks:
  traefik-proxy:
    external: true
