api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
    http:
      middlewares:
        - secureHeaders@file
      tls:
        #certResolver: le-dns
        certResolver: zerossl
        domains:
          - main: le-5ra.de
            sans:
              - "*.le-5ra.de"
              
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: fm.maghraoui@gmail.com
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
        
  le-dns:
    acme:
      email: fm.maghraoui@gmail.com
      storage: acme.json
      keyType: EC384
      dnsChallenge:
        provider: acme-dns

  zerossl:
    acme:
      caServer: https://acme.zerossl.com/v2/DV90
      email: fm.maghraoui@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: acme-dns
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
      eab:
        kid: mB46MFu4KLaibkcKlQpugg
        hmacEncoded: Bq8-JSCM7HzZA_mZwZpjsLrnJ3IJZGuGKfLqaYwwfnhXYrVlo-i7MXQvsJic4_sLCMl9QHlfVKE0fR5NLHl5LQ
